#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DotaDB")]
	public partial class MyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHero(Hero instance);
    partial void UpdateHero(Hero instance);
    partial void DeleteHero(Hero instance);
    partial void InsertTeam(Team instance);
    partial void UpdateTeam(Team instance);
    partial void DeleteTeam(Team instance);
    partial void InsertMatch(Match instance);
    partial void UpdateMatch(Match instance);
    partial void DeleteMatch(Match instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertMResult(MResult instance);
    partial void UpdateMResult(MResult instance);
    partial void DeleteMResult(MResult instance);
    partial void InsertBet(Bet instance);
    partial void UpdateBet(Bet instance);
    partial void DeleteBet(Bet instance);
    partial void InsertMatchP(MatchP instance);
    partial void UpdateMatchP(MatchP instance);
    partial void DeleteMatchP(MatchP instance);
    partial void InsertUserPrediction(UserPrediction instance);
    partial void UpdateUserPrediction(UserPrediction instance);
    partial void DeleteUserPrediction(UserPrediction instance);
    #endregion
		
		public MyDBDataContext() : 
				base(global::OOP2.Properties.Settings.Default.DotaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hero> Heros
		{
			get
			{
				return this.GetTable<Hero>();
			}
		}
		
		public System.Data.Linq.Table<Team> Teams
		{
			get
			{
				return this.GetTable<Team>();
			}
		}
		
		public System.Data.Linq.Table<Match> Matches
		{
			get
			{
				return this.GetTable<Match>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<MResult> MResults
		{
			get
			{
				return this.GetTable<MResult>();
			}
		}
		
		public System.Data.Linq.Table<Bet> Bets
		{
			get
			{
				return this.GetTable<Bet>();
			}
		}
		
		public System.Data.Linq.Table<MatchP> MatchPs
		{
			get
			{
				return this.GetTable<MatchP>();
			}
		}
		
		public System.Data.Linq.Table<UserPrediction> UserPredictions
		{
			get
			{
				return this.GetTable<UserPrediction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hero")]
	public partial class Hero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Hero()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Team")]
	public partial class Team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _IconPath;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIconPathChanging(string value);
    partial void OnIconPathChanged();
    #endregion
		
		public Team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconPath", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IconPath
		{
			get
			{
				return this._IconPath;
			}
			set
			{
				if ((this._IconPath != value))
				{
					this.OnIconPathChanging(value);
					this.SendPropertyChanging();
					this._IconPath = value;
					this.SendPropertyChanged("IconPath");
					this.OnIconPathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Match")]
	public partial class Match : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchId;
		
		private string _Dire;
		
		private string _Radient;
		
		private System.DateTime _Time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchIdChanging(int value);
    partial void OnMatchIdChanged();
    partial void OnDireChanging(string value);
    partial void OnDireChanged();
    partial void OnRadientChanging(string value);
    partial void OnRadientChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    #endregion
		
		public Match()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MatchId
		{
			get
			{
				return this._MatchId;
			}
			set
			{
				if ((this._MatchId != value))
				{
					this.OnMatchIdChanging(value);
					this.SendPropertyChanging();
					this._MatchId = value;
					this.SendPropertyChanged("MatchId");
					this.OnMatchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dire", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dire
		{
			get
			{
				return this._Dire;
			}
			set
			{
				if ((this._Dire != value))
				{
					this.OnDireChanging(value);
					this.SendPropertyChanging();
					this._Dire = value;
					this.SendPropertyChanged("Dire");
					this.OnDireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radient", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Radient
		{
			get
			{
				return this._Radient;
			}
			set
			{
				if ((this._Radient != value))
				{
					this.OnRadientChanging(value);
					this.SendPropertyChanging();
					this._Radient = value;
					this.SendPropertyChanged("Radient");
					this.OnRadientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private string _Password;
		
		private int _IGC;
		
		private string _AboutSelf;
		
		private string _Picture;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIGCChanging(int value);
    partial void OnIGCChanged();
    partial void OnAboutSelfChanging(string value);
    partial void OnAboutSelfChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGC", DbType="Int NOT NULL")]
		public int IGC
		{
			get
			{
				return this._IGC;
			}
			set
			{
				if ((this._IGC != value))
				{
					this.OnIGCChanging(value);
					this.SendPropertyChanging();
					this._IGC = value;
					this.SendPropertyChanged("IGC");
					this.OnIGCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutSelf", DbType="VarChar(MAX)")]
		public string AboutSelf
		{
			get
			{
				return this._AboutSelf;
			}
			set
			{
				if ((this._AboutSelf != value))
				{
					this.OnAboutSelfChanging(value);
					this.SendPropertyChanging();
					this._AboutSelf = value;
					this.SendPropertyChanged("AboutSelf");
					this.OnAboutSelfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarChar(MAX)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminId;
		
		private string _UserName;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIdChanging(int value);
    partial void OnAdminIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AdminId
		{
			get
			{
				return this._AdminId;
			}
			set
			{
				if ((this._AdminId != value))
				{
					this.OnAdminIdChanging(value);
					this.SendPropertyChanging();
					this._AdminId = value;
					this.SendPropertyChanged("AdminId");
					this.OnAdminIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MResult")]
	public partial class MResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchId;
		
		private string _Win;
		
		private string _Hero1;
		
		private string _Hero2;
		
		private string _Hero3;
		
		private string _Hero4;
		
		private string _Hero5;
		
		private string _Hero6;
		
		private string _Hero7;
		
		private string _Hero8;
		
		private string _Hero9;
		
		private string _Hero10;
		
		private System.Nullable<int> _RadientScore;
		
		private System.Nullable<int> _DireScore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchIdChanging(int value);
    partial void OnMatchIdChanged();
    partial void OnWinChanging(string value);
    partial void OnWinChanged();
    partial void OnHero1Changing(string value);
    partial void OnHero1Changed();
    partial void OnHero2Changing(string value);
    partial void OnHero2Changed();
    partial void OnHero3Changing(string value);
    partial void OnHero3Changed();
    partial void OnHero4Changing(string value);
    partial void OnHero4Changed();
    partial void OnHero5Changing(string value);
    partial void OnHero5Changed();
    partial void OnHero6Changing(string value);
    partial void OnHero6Changed();
    partial void OnHero7Changing(string value);
    partial void OnHero7Changed();
    partial void OnHero8Changing(string value);
    partial void OnHero8Changed();
    partial void OnHero9Changing(string value);
    partial void OnHero9Changed();
    partial void OnHero10Changing(string value);
    partial void OnHero10Changed();
    partial void OnRadientScoreChanging(System.Nullable<int> value);
    partial void OnRadientScoreChanged();
    partial void OnDireScoreChanging(System.Nullable<int> value);
    partial void OnDireScoreChanged();
    #endregion
		
		public MResult()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MatchId
		{
			get
			{
				return this._MatchId;
			}
			set
			{
				if ((this._MatchId != value))
				{
					this.OnMatchIdChanging(value);
					this.SendPropertyChanging();
					this._MatchId = value;
					this.SendPropertyChanged("MatchId");
					this.OnMatchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="VarChar(50)")]
		public string Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero1", DbType="VarChar(50)")]
		public string Hero1
		{
			get
			{
				return this._Hero1;
			}
			set
			{
				if ((this._Hero1 != value))
				{
					this.OnHero1Changing(value);
					this.SendPropertyChanging();
					this._Hero1 = value;
					this.SendPropertyChanged("Hero1");
					this.OnHero1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero2", DbType="VarChar(50)")]
		public string Hero2
		{
			get
			{
				return this._Hero2;
			}
			set
			{
				if ((this._Hero2 != value))
				{
					this.OnHero2Changing(value);
					this.SendPropertyChanging();
					this._Hero2 = value;
					this.SendPropertyChanged("Hero2");
					this.OnHero2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero3", DbType="VarChar(50)")]
		public string Hero3
		{
			get
			{
				return this._Hero3;
			}
			set
			{
				if ((this._Hero3 != value))
				{
					this.OnHero3Changing(value);
					this.SendPropertyChanging();
					this._Hero3 = value;
					this.SendPropertyChanged("Hero3");
					this.OnHero3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero4", DbType="VarChar(50)")]
		public string Hero4
		{
			get
			{
				return this._Hero4;
			}
			set
			{
				if ((this._Hero4 != value))
				{
					this.OnHero4Changing(value);
					this.SendPropertyChanging();
					this._Hero4 = value;
					this.SendPropertyChanged("Hero4");
					this.OnHero4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero5", DbType="VarChar(50)")]
		public string Hero5
		{
			get
			{
				return this._Hero5;
			}
			set
			{
				if ((this._Hero5 != value))
				{
					this.OnHero5Changing(value);
					this.SendPropertyChanging();
					this._Hero5 = value;
					this.SendPropertyChanged("Hero5");
					this.OnHero5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero6", DbType="VarChar(50)")]
		public string Hero6
		{
			get
			{
				return this._Hero6;
			}
			set
			{
				if ((this._Hero6 != value))
				{
					this.OnHero6Changing(value);
					this.SendPropertyChanging();
					this._Hero6 = value;
					this.SendPropertyChanged("Hero6");
					this.OnHero6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero7", DbType="VarChar(50)")]
		public string Hero7
		{
			get
			{
				return this._Hero7;
			}
			set
			{
				if ((this._Hero7 != value))
				{
					this.OnHero7Changing(value);
					this.SendPropertyChanging();
					this._Hero7 = value;
					this.SendPropertyChanged("Hero7");
					this.OnHero7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero8", DbType="VarChar(50)")]
		public string Hero8
		{
			get
			{
				return this._Hero8;
			}
			set
			{
				if ((this._Hero8 != value))
				{
					this.OnHero8Changing(value);
					this.SendPropertyChanging();
					this._Hero8 = value;
					this.SendPropertyChanged("Hero8");
					this.OnHero8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero9", DbType="VarChar(50)")]
		public string Hero9
		{
			get
			{
				return this._Hero9;
			}
			set
			{
				if ((this._Hero9 != value))
				{
					this.OnHero9Changing(value);
					this.SendPropertyChanging();
					this._Hero9 = value;
					this.SendPropertyChanged("Hero9");
					this.OnHero9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero10", DbType="VarChar(50)")]
		public string Hero10
		{
			get
			{
				return this._Hero10;
			}
			set
			{
				if ((this._Hero10 != value))
				{
					this.OnHero10Changing(value);
					this.SendPropertyChanging();
					this._Hero10 = value;
					this.SendPropertyChanged("Hero10");
					this.OnHero10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadientScore", DbType="Int")]
		public System.Nullable<int> RadientScore
		{
			get
			{
				return this._RadientScore;
			}
			set
			{
				if ((this._RadientScore != value))
				{
					this.OnRadientScoreChanging(value);
					this.SendPropertyChanging();
					this._RadientScore = value;
					this.SendPropertyChanged("RadientScore");
					this.OnRadientScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireScore", DbType="Int")]
		public System.Nullable<int> DireScore
		{
			get
			{
				return this._DireScore;
			}
			set
			{
				if ((this._DireScore != value))
				{
					this.OnDireScoreChanging(value);
					this.SendPropertyChanging();
					this._DireScore = value;
					this.SendPropertyChanged("DireScore");
					this.OnDireScoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bets")]
	public partial class Bet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private int _MatchId;
		
		private System.Nullable<int> _Section1;
		
		private System.Nullable<int> _Section2;
		
		private System.Nullable<int> _Section3;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnMatchIdChanging(int value);
    partial void OnMatchIdChanged();
    partial void OnSection1Changing(System.Nullable<int> value);
    partial void OnSection1Changed();
    partial void OnSection2Changing(System.Nullable<int> value);
    partial void OnSection2Changed();
    partial void OnSection3Changing(System.Nullable<int> value);
    partial void OnSection3Changed();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Bet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchId", DbType="Int NOT NULL")]
		public int MatchId
		{
			get
			{
				return this._MatchId;
			}
			set
			{
				if ((this._MatchId != value))
				{
					this.OnMatchIdChanging(value);
					this.SendPropertyChanging();
					this._MatchId = value;
					this.SendPropertyChanged("MatchId");
					this.OnMatchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section1", DbType="Int")]
		public System.Nullable<int> Section1
		{
			get
			{
				return this._Section1;
			}
			set
			{
				if ((this._Section1 != value))
				{
					this.OnSection1Changing(value);
					this.SendPropertyChanging();
					this._Section1 = value;
					this.SendPropertyChanged("Section1");
					this.OnSection1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section2", DbType="Int")]
		public System.Nullable<int> Section2
		{
			get
			{
				return this._Section2;
			}
			set
			{
				if ((this._Section2 != value))
				{
					this.OnSection2Changing(value);
					this.SendPropertyChanging();
					this._Section2 = value;
					this.SendPropertyChanged("Section2");
					this.OnSection2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3", DbType="Int")]
		public System.Nullable<int> Section3
		{
			get
			{
				return this._Section3;
			}
			set
			{
				if ((this._Section3 != value))
				{
					this.OnSection3Changing(value);
					this.SendPropertyChanging();
					this._Section3 = value;
					this.SendPropertyChanged("Section3");
					this.OnSection3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MatchP")]
	public partial class MatchP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchId;
		
		private string _Username;
		
		private string _Win;
		
		private string _Hero1;
		
		private string _Hero2;
		
		private string _Hero3;
		
		private string _Hero4;
		
		private string _Hero5;
		
		private string _Hero6;
		
		private string _Hero7;
		
		private string _Hero8;
		
		private string _Hero9;
		
		private string _Hero10;
		
		private System.Nullable<int> _RadientScore;
		
		private System.Nullable<int> _DireScore;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchIdChanging(int value);
    partial void OnMatchIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnWinChanging(string value);
    partial void OnWinChanged();
    partial void OnHero1Changing(string value);
    partial void OnHero1Changed();
    partial void OnHero2Changing(string value);
    partial void OnHero2Changed();
    partial void OnHero3Changing(string value);
    partial void OnHero3Changed();
    partial void OnHero4Changing(string value);
    partial void OnHero4Changed();
    partial void OnHero5Changing(string value);
    partial void OnHero5Changed();
    partial void OnHero6Changing(string value);
    partial void OnHero6Changed();
    partial void OnHero7Changing(string value);
    partial void OnHero7Changed();
    partial void OnHero8Changing(string value);
    partial void OnHero8Changed();
    partial void OnHero9Changing(string value);
    partial void OnHero9Changed();
    partial void OnHero10Changing(string value);
    partial void OnHero10Changed();
    partial void OnRadientScoreChanging(System.Nullable<int> value);
    partial void OnRadientScoreChanged();
    partial void OnDireScoreChanging(System.Nullable<int> value);
    partial void OnDireScoreChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public MatchP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchId", DbType="Int NOT NULL")]
		public int MatchId
		{
			get
			{
				return this._MatchId;
			}
			set
			{
				if ((this._MatchId != value))
				{
					this.OnMatchIdChanging(value);
					this.SendPropertyChanging();
					this._MatchId = value;
					this.SendPropertyChanged("MatchId");
					this.OnMatchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="VarChar(50)")]
		public string Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero1", DbType="VarChar(50)")]
		public string Hero1
		{
			get
			{
				return this._Hero1;
			}
			set
			{
				if ((this._Hero1 != value))
				{
					this.OnHero1Changing(value);
					this.SendPropertyChanging();
					this._Hero1 = value;
					this.SendPropertyChanged("Hero1");
					this.OnHero1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero2", DbType="VarChar(50)")]
		public string Hero2
		{
			get
			{
				return this._Hero2;
			}
			set
			{
				if ((this._Hero2 != value))
				{
					this.OnHero2Changing(value);
					this.SendPropertyChanging();
					this._Hero2 = value;
					this.SendPropertyChanged("Hero2");
					this.OnHero2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero3", DbType="VarChar(50)")]
		public string Hero3
		{
			get
			{
				return this._Hero3;
			}
			set
			{
				if ((this._Hero3 != value))
				{
					this.OnHero3Changing(value);
					this.SendPropertyChanging();
					this._Hero3 = value;
					this.SendPropertyChanged("Hero3");
					this.OnHero3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero4", DbType="VarChar(50)")]
		public string Hero4
		{
			get
			{
				return this._Hero4;
			}
			set
			{
				if ((this._Hero4 != value))
				{
					this.OnHero4Changing(value);
					this.SendPropertyChanging();
					this._Hero4 = value;
					this.SendPropertyChanged("Hero4");
					this.OnHero4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero5", DbType="VarChar(50)")]
		public string Hero5
		{
			get
			{
				return this._Hero5;
			}
			set
			{
				if ((this._Hero5 != value))
				{
					this.OnHero5Changing(value);
					this.SendPropertyChanging();
					this._Hero5 = value;
					this.SendPropertyChanged("Hero5");
					this.OnHero5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero6", DbType="VarChar(50)")]
		public string Hero6
		{
			get
			{
				return this._Hero6;
			}
			set
			{
				if ((this._Hero6 != value))
				{
					this.OnHero6Changing(value);
					this.SendPropertyChanging();
					this._Hero6 = value;
					this.SendPropertyChanged("Hero6");
					this.OnHero6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero7", DbType="VarChar(50)")]
		public string Hero7
		{
			get
			{
				return this._Hero7;
			}
			set
			{
				if ((this._Hero7 != value))
				{
					this.OnHero7Changing(value);
					this.SendPropertyChanging();
					this._Hero7 = value;
					this.SendPropertyChanged("Hero7");
					this.OnHero7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero8", DbType="VarChar(50)")]
		public string Hero8
		{
			get
			{
				return this._Hero8;
			}
			set
			{
				if ((this._Hero8 != value))
				{
					this.OnHero8Changing(value);
					this.SendPropertyChanging();
					this._Hero8 = value;
					this.SendPropertyChanged("Hero8");
					this.OnHero8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero9", DbType="VarChar(50)")]
		public string Hero9
		{
			get
			{
				return this._Hero9;
			}
			set
			{
				if ((this._Hero9 != value))
				{
					this.OnHero9Changing(value);
					this.SendPropertyChanging();
					this._Hero9 = value;
					this.SendPropertyChanged("Hero9");
					this.OnHero9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero10", DbType="VarChar(50)")]
		public string Hero10
		{
			get
			{
				return this._Hero10;
			}
			set
			{
				if ((this._Hero10 != value))
				{
					this.OnHero10Changing(value);
					this.SendPropertyChanging();
					this._Hero10 = value;
					this.SendPropertyChanged("Hero10");
					this.OnHero10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadientScore", DbType="Int")]
		public System.Nullable<int> RadientScore
		{
			get
			{
				return this._RadientScore;
			}
			set
			{
				if ((this._RadientScore != value))
				{
					this.OnRadientScoreChanging(value);
					this.SendPropertyChanging();
					this._RadientScore = value;
					this.SendPropertyChanged("RadientScore");
					this.OnRadientScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireScore", DbType="Int")]
		public System.Nullable<int> DireScore
		{
			get
			{
				return this._DireScore;
			}
			set
			{
				if ((this._DireScore != value))
				{
					this.OnDireScoreChanging(value);
					this.SendPropertyChanging();
					this._DireScore = value;
					this.SendPropertyChanged("DireScore");
					this.OnDireScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserPrediction")]
	public partial class UserPrediction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MatchId;
		
		private string _Username;
		
		private string _Win;
		
		private string _Hero1;
		
		private string _Hero2;
		
		private string _Hero3;
		
		private string _Hero4;
		
		private string _Hero5;
		
		private string _Hero6;
		
		private string _Hero7;
		
		private string _Hero8;
		
		private string _Hero9;
		
		private string _Hero10;
		
		private int _RadientScore;
		
		private int _DireScore;
		
		private string _S1_Bet_Won;
		
		private string _S2_Bet_Won;
		
		private string _S3_Bet_Won;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatchIdChanging(int value);
    partial void OnMatchIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnWinChanging(string value);
    partial void OnWinChanged();
    partial void OnHero1Changing(string value);
    partial void OnHero1Changed();
    partial void OnHero2Changing(string value);
    partial void OnHero2Changed();
    partial void OnHero3Changing(string value);
    partial void OnHero3Changed();
    partial void OnHero4Changing(string value);
    partial void OnHero4Changed();
    partial void OnHero5Changing(string value);
    partial void OnHero5Changed();
    partial void OnHero6Changing(string value);
    partial void OnHero6Changed();
    partial void OnHero7Changing(string value);
    partial void OnHero7Changed();
    partial void OnHero8Changing(string value);
    partial void OnHero8Changed();
    partial void OnHero9Changing(string value);
    partial void OnHero9Changed();
    partial void OnHero10Changing(string value);
    partial void OnHero10Changed();
    partial void OnRadientScoreChanging(int value);
    partial void OnRadientScoreChanged();
    partial void OnDireScoreChanging(int value);
    partial void OnDireScoreChanged();
    partial void OnS1_Bet_WonChanging(string value);
    partial void OnS1_Bet_WonChanged();
    partial void OnS2_Bet_WonChanging(string value);
    partial void OnS2_Bet_WonChanged();
    partial void OnS3_Bet_WonChanging(string value);
    partial void OnS3_Bet_WonChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public UserPrediction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchId", DbType="Int NOT NULL")]
		public int MatchId
		{
			get
			{
				return this._MatchId;
			}
			set
			{
				if ((this._MatchId != value))
				{
					this.OnMatchIdChanging(value);
					this.SendPropertyChanging();
					this._MatchId = value;
					this.SendPropertyChanged("MatchId");
					this.OnMatchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero1
		{
			get
			{
				return this._Hero1;
			}
			set
			{
				if ((this._Hero1 != value))
				{
					this.OnHero1Changing(value);
					this.SendPropertyChanging();
					this._Hero1 = value;
					this.SendPropertyChanged("Hero1");
					this.OnHero1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero2
		{
			get
			{
				return this._Hero2;
			}
			set
			{
				if ((this._Hero2 != value))
				{
					this.OnHero2Changing(value);
					this.SendPropertyChanging();
					this._Hero2 = value;
					this.SendPropertyChanged("Hero2");
					this.OnHero2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero3", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero3
		{
			get
			{
				return this._Hero3;
			}
			set
			{
				if ((this._Hero3 != value))
				{
					this.OnHero3Changing(value);
					this.SendPropertyChanging();
					this._Hero3 = value;
					this.SendPropertyChanged("Hero3");
					this.OnHero3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero4", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero4
		{
			get
			{
				return this._Hero4;
			}
			set
			{
				if ((this._Hero4 != value))
				{
					this.OnHero4Changing(value);
					this.SendPropertyChanging();
					this._Hero4 = value;
					this.SendPropertyChanged("Hero4");
					this.OnHero4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero5", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero5
		{
			get
			{
				return this._Hero5;
			}
			set
			{
				if ((this._Hero5 != value))
				{
					this.OnHero5Changing(value);
					this.SendPropertyChanging();
					this._Hero5 = value;
					this.SendPropertyChanged("Hero5");
					this.OnHero5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero6", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero6
		{
			get
			{
				return this._Hero6;
			}
			set
			{
				if ((this._Hero6 != value))
				{
					this.OnHero6Changing(value);
					this.SendPropertyChanging();
					this._Hero6 = value;
					this.SendPropertyChanged("Hero6");
					this.OnHero6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero7", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero7
		{
			get
			{
				return this._Hero7;
			}
			set
			{
				if ((this._Hero7 != value))
				{
					this.OnHero7Changing(value);
					this.SendPropertyChanging();
					this._Hero7 = value;
					this.SendPropertyChanged("Hero7");
					this.OnHero7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero8", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero8
		{
			get
			{
				return this._Hero8;
			}
			set
			{
				if ((this._Hero8 != value))
				{
					this.OnHero8Changing(value);
					this.SendPropertyChanging();
					this._Hero8 = value;
					this.SendPropertyChanged("Hero8");
					this.OnHero8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero9", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero9
		{
			get
			{
				return this._Hero9;
			}
			set
			{
				if ((this._Hero9 != value))
				{
					this.OnHero9Changing(value);
					this.SendPropertyChanging();
					this._Hero9 = value;
					this.SendPropertyChanged("Hero9");
					this.OnHero9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hero10", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hero10
		{
			get
			{
				return this._Hero10;
			}
			set
			{
				if ((this._Hero10 != value))
				{
					this.OnHero10Changing(value);
					this.SendPropertyChanging();
					this._Hero10 = value;
					this.SendPropertyChanged("Hero10");
					this.OnHero10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadientScore", DbType="Int NOT NULL")]
		public int RadientScore
		{
			get
			{
				return this._RadientScore;
			}
			set
			{
				if ((this._RadientScore != value))
				{
					this.OnRadientScoreChanging(value);
					this.SendPropertyChanging();
					this._RadientScore = value;
					this.SendPropertyChanged("RadientScore");
					this.OnRadientScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireScore", DbType="Int NOT NULL")]
		public int DireScore
		{
			get
			{
				return this._DireScore;
			}
			set
			{
				if ((this._DireScore != value))
				{
					this.OnDireScoreChanging(value);
					this.SendPropertyChanging();
					this._DireScore = value;
					this.SendPropertyChanged("DireScore");
					this.OnDireScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[S1 Bet-Won]", Storage="_S1_Bet_Won", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string S1_Bet_Won
		{
			get
			{
				return this._S1_Bet_Won;
			}
			set
			{
				if ((this._S1_Bet_Won != value))
				{
					this.OnS1_Bet_WonChanging(value);
					this.SendPropertyChanging();
					this._S1_Bet_Won = value;
					this.SendPropertyChanged("S1_Bet_Won");
					this.OnS1_Bet_WonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[S2 Bet-Won]", Storage="_S2_Bet_Won", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string S2_Bet_Won
		{
			get
			{
				return this._S2_Bet_Won;
			}
			set
			{
				if ((this._S2_Bet_Won != value))
				{
					this.OnS2_Bet_WonChanging(value);
					this.SendPropertyChanging();
					this._S2_Bet_Won = value;
					this.SendPropertyChanged("S2_Bet_Won");
					this.OnS2_Bet_WonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[S3 Bet-Won]", Storage="_S3_Bet_Won", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string S3_Bet_Won
		{
			get
			{
				return this._S3_Bet_Won;
			}
			set
			{
				if ((this._S3_Bet_Won != value))
				{
					this.OnS3_Bet_WonChanging(value);
					this.SendPropertyChanging();
					this._S3_Bet_Won = value;
					this.SendPropertyChanged("S3_Bet_Won");
					this.OnS3_Bet_WonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
